import { createContext } from 'reka-ui'

export { default as GithubContainer } from './GithubContainer.vue'
export { default as GithubAverageCommitsPerWeek } from './GithubAverageCommitsPerWeek.vue'
export { default as GithubCommitsTotal } from './GithubCommitsTotal.vue'
export { default as GithubContributionGraphBlocks } from './GithubContributionGraphBlocks.vue'
export { default as GithubContributionGraphMonths } from './GithubContributionGraphMonths.vue'
export { default as GithubLongestGap } from './GithubLongestGap.vue'
export { default as GithubLongestStreak } from './GithubLongestStreak.vue'
export { default as GithubMostActiveMonth } from './GithubMostActiveMonth.vue'
export { default as GithubMostCommitsDay } from './GithubMostCommitsDay.vue'
export { default as GithubPullRequestsTotal } from './GithubPullRequestsTotal.vue'
export { default as GithubStarsTotal } from './GithubStarsTotal.vue'
export { default as GithubTopLanguages } from './GithubTopLanguages.vue'
export { default as GithubTopRepository } from './GithubTopRepository.vue'
export { default as GithubTotalIssues } from './GithubTotalIssues.vue'
export { default as GithubWeekendActivity } from './GithubWeekendActivity.vue'
export { default as GithubTopRepositoryItems } from './GithubTopRepositoryItems.vue'

export const [providerGithubData, useGithubData] = createContext<any>('GithubData')
